VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "pc0" do |pc0|
        pc0.vm.hostname = "pc0"
        pc0.vm.network :private_network, ip: "192.168.5.2"
    end
    config.vm.box = "labreti/labvm"
    config.ssh.forward_x11 = true
end
